import {readFile,mkdir,writeFile} from "node:fs/promises";
import {escape as h,safeJson} from "../src/core.mjs";
const snapshot=JSON.parse(await readFile("data/snapshot.json","utf8"));
const sources=JSON.parse(await readFile("config/sources.json","utf8"));
const channels=JSON.parse(await readFile("config/channels.json","utf8"));
const site=JSON.parse(await readFile("config/site.json","utf8"));
const deploymentUrl=new URL(process.env.SITE_URL??site.siteUrl);
deploymentUrl.protocol="https:";
const base=deploymentUrl.href.replace(/\/+$/,"")+"/";
const prefix=new URL(base).pathname;
const items=snapshot.items;const sourceMap=new Map(sources.map(s=>[s.id,s]));
const href=path=>prefix+path;const absolute=path=>base+path;
const date=t=>t?new Intl.DateTimeFormat("zh-CN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Shanghai"}).format(new Date(t)):"原文未标注时间";
const totals=new Map(channels.map(c=>[c.slug,items.filter(i=>i.channels.includes(c.slug)).length]));
const excerptHtml=i=>i.summary?'<section class="content-excerpt"><h2>资讯摘要</h2><p>'+h(i.summary)+'</p><small>摘自发布方公开订阅源 · '+h(sourceMap.get(i.summaryProvenance?.sourceId)?.name??sourceNames(i))+' · 固定截取，未经独立核验</small></section>':'<p class="notice">该来源未提供摘要，完整内容请阅读原文。</p>';
const sourceNames=i=>i.sourceIds.map(id=>sourceMap.get(id)?.name??id).join(" / ");
const style=await readFile("src/site.css","utf8");const written=[];
async function output(path,text){await mkdir("dist/"+path.split("/").slice(0,-1).join("/"),{recursive:true});await writeFile("dist/"+path,text);written.push(path);}
function layout(title,description,path,body,active="all",structured=null,noindex=false){
 const nav=channels.map(c=>'<a class="'+(active===c.slug?'selected':'')+'" href="'+href("channels/"+c.slug+"/")+'"><span>'+h(c.name)+'</span><small>'+totals.get(c.slug)+'</small></a>').join("");
 return '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+h(title)+' · 世界信息汇</title><meta name="description" content="'+h(description)+'"><link rel="canonical" href="'+h(absolute(path))+'"><meta name="robots" content="'+(noindex?'noindex,follow':'index,follow')+'"><link rel="stylesheet" href="'+href("site.css")+'"><link rel="alternate" type="application/rss+xml" href="'+href("rss.xml")+'"><link rel="alternate" type="application/atom+xml" href="'+href("atom.xml")+'"><link rel="alternate" type="application/feed+json" href="'+href("feed.json")+'">'+(structured?'<script type="application/ld+json">'+safeJson(structured)+'</script>':'')+'</head><body><header><a class="brand" href="'+href("")+'"><span class="logo">W</span><span>世界信息汇<small>WORLD INFORMATION HUB</small></span></a><nav class="topnav"><a href="'+href("")+'">资讯</a><a href="'+href("sources/")+'">来源</a><a href="'+href("about/")+'">关于</a><a class="subscribe" href="'+href("feed.json")+'">订阅更新 ↗</a></nav></header><div class="workspace"><aside class="sidebar"><p class="navlabel">行业频道</p><nav aria-label="行业频道"><a class="'+(active==='all'?'selected':'')+'" href="'+href("")+'"><span>全部资讯</span><small>'+items.length+'</small></a>'+nav+'</nav><div class="sidebar-note"><span class="status-dot"></span> 云端自动汇集<br/><small>摘要 · 来源 · 原文链接<br/>不使用模型生成内容</small></div></aside><main>'+body+'</main></div><footer><span>世界信息汇 · 资讯归属原发布方</span><div><a href="'+href("rss.xml")+'">RSS</a><a href="'+href("atom.xml")+'">Atom</a><a href="'+href("feed.json")+'">JSON Feed</a><a href="'+href("api/v1/articles.json")+'">数据</a></div></footer><script src="'+href("site.js")+'" defer></script></body></html>';
}
function card(i){
 const c=channels.find(c=>c.slug===i.channels[0]);
 return '<article class="news-item" data-title="'+h(i.title.toLowerCase())+'" data-source="'+h(sourceNames(i).toLowerCase())+'"><div class="item-heading"><span class="tag">'+h(c?.name??"综合")+'</span><time'+(i.sourcePublishedAt?' datetime="'+h(i.sourcePublishedAt)+'"':'')+'>'+h(date(i.sourcePublishedAt))+(i.timeIssue==="future_date"?"（来源标注，时间待核验）":"")+'</time></div><h2><a href="'+href("articles/"+i.id+"/")+'">'+h(i.title)+'</a></h2>'+(i.summary?'<p class="card-excerpt">'+h(i.summary)+'</p>':'')+'<div class="item-footer"><span>'+h(sourceNames(i))+'</span><a href="'+h(i.originalUrl)+'" rel="noopener noreferrer" target="_blank">阅读原文 ↗</a></div></article>';
}
function pagination(page,pages,basePath){
 if(pages<=1)return "";const links=[];for(let p=1;p<=pages;p++)if(p===1||p===pages||Math.abs(p-page)<=2)links.push('<a '+(p===page?'aria-current="page" class="current"':'')+' href="'+href(basePath+(p===1?'':'page/'+p+'/'))+'">'+p+'</a>');
 return '<nav class="pagination" aria-label="分页">'+(page>1?'<a href="'+href(basePath+(page===2?'':'page/'+(page-1)+'/'))+'">← 上一页</a>':'')+links.join("")+(page<pages?'<a href="'+href(basePath+"page/"+(page+1)+"/")+'">下一页 →</a>':'')+'</nav>';
}
async function listing(records,channel=null){
 const pages=Math.max(1,Math.ceil(records.length/site.perPage));const basePath=channel?"channels/"+channel.slug+"/":"";
 for(let page=1;page<=pages;page++){
  const path=basePath+(page===1?"":"page/"+page+"/");
  const latest=records.slice((page-1)*site.perPage,page*site.perPage);
  const heading=channel?channel.name:"今天，世界有哪些新动态？";
  const desc=channel?channel.description:"从科技到日常生活，按来源追踪最新资讯。";
  const body='<section class="page-head"><div><p class="eyebrow">'+(channel?'INDUSTRY FEED':'LIVE INFORMATION INDEX')+'</p><h1>'+h(heading)+'</h1><p>'+h(desc)+'</p></div><div class="summary-number"><strong>'+records.length+'</strong><span>条来源记录</span></div></section><section class="toolbar"><div><span class="status-dot"></span> 最近检查：'+h(date(snapshot.collectedAt))+'<small> · 计划每30分钟更新</small></div><label class="search"><span>筛选</span><input id="search" type="search" placeholder="搜索当前页标题或来源" aria-label="筛选当前页文章"></label></section><p class="filter-state" id="filter-state" hidden></p><section class="news-grid">'+(latest.length?latest.map(card).join(""):'<p class="empty">本轮来源中暂无匹配记录，自动监控将持续收录。<br/>分类依据来源栏目与标题关键词。</p>')+'</section>'+pagination(page,pages,basePath);
  await output(path+"index.html",layout((channel?channel.name:"最新资讯")+(page>1?" · 第"+page+"页":""),desc,path,body,channel?.slug??"all"));
 }
}
await output("site.css",style);
await output("site.js",'const search=document.getElementById("search");if(search){search.addEventListener("input",()=>{const q=search.value.toLowerCase().trim();let shown=0;for(const item of document.querySelectorAll(".news-item")){item.hidden=!!q&&!((item.dataset.title+" "+item.dataset.source).includes(q));if(!item.hidden)shown++;}const state=document.getElementById("filter-state");state.hidden=!q;state.textContent="当前页匹配 "+shown+" 条；其他文章请按频道或分页浏览。";});}');
await listing(items);for(const channel of channels)await listing(items.filter(i=>i.channels.includes(channel.slug)),channel);
for(const i of items){
 const path="articles/"+i.id+"/";const evidenceSources=i.sourceIds.map(id=>sourceMap.get(id)).filter(Boolean);
 const body='<article class="record"><a class="back" href="'+href("")+'">← 返回资讯</a><p class="eyebrow">SOURCE RECORD / 来源记录</p><h1>'+h(i.title)+'</h1><div class="record-meta"><span>'+h(sourceNames(i))+'</span><time'+(i.sourcePublishedAt?' datetime="'+h(i.sourcePublishedAt)+'"':'')+'>'+h(date(i.sourcePublishedAt))+'</time><span>版本 '+i.version+'</span></div>'+excerptHtml(i)+'<section class="original-panel"><span class="tag">原文导航</span><p>这是一条来自 '+h(sourceNames(i))+' 的资讯记录。本站展示发布方公开订阅源的有限摘要、时间和链接；完整内容由原发布方提供。</p><a class="primary" href="'+h(i.originalUrl)+'" rel="noopener noreferrer" target="_blank">打开原文 ↗</a><p class="url-text">'+h(i.originalUrl)+'</p></section><h2>来源与追踪</h2><dl><dt>原文地址</dt><dd><a href="'+h(i.originalUrl)+'">'+h(i.originalUrl)+'</a></dd><dt>发布来源</dt><dd>'+evidenceSources.map(s=>'<a href="'+h(s.baseUrl)+'">'+h(s.name)+'</a>').join(' / ')+'</dd><dt>首次收录</dt><dd>'+h(date(i.firstSeenAt))+'</dd><dt>最近发现</dt><dd>'+h(date(i.lastSeenAt))+'</dd><dt>记录更新</dt><dd>'+h(date(i.updatedAt))+'</dd><dt>分类依据</dt><dd>来源栏目与标题关键词匹配</dd></dl>'+(i.timeIssue?'<p class="notice">原文时间'+(i.timeIssue==="future_date"?'晚于收录检查时间':'未提供')+'，请以原发布方页面为准。</p>':'')+'<h2>相关频道</h2><div class="topic-links">'+i.channels.map(slug=>'<a href="'+href("channels/"+slug+"/")+'">'+h(channels.find(c=>c.slug===slug)?.name??slug)+'</a>').join("")+'</div>'+(i.history.length?'<h2>变更记录</h2><ul>'+i.history.map(v=>'<li>v'+v.version+' · '+h(v.title)+' · '+h(date(v.updatedAt))+'</li>').join(""):'')+'<p class="data-link"><a href="'+href("api/v1/articles/"+i.id+".json")+'">读取此条目的机器数据 →</a></p></article>';
 const structured={"@context":"https://schema.org","@type":"CreativeWork","@id":absolute(path),name:i.title,url:absolute(path),isBasedOn:i.originalUrl,dateCreated:i.firstSeenAt,dateModified:i.updatedAt,description:i.summary??"来源未提供摘要。",text:i.summary??undefined,citation:i.originalUrl};
 await output(path+"index.html",layout(i.title,"查看来源、原文地址、发布时间和收录历史。",path,body,i.channels[0],structured));
 await output("api/v1/articles/"+i.id+".json",JSON.stringify({data:i,meta:{schemaVersion:"1",type:"source_record"}},null,2));
}
const healthy=sources.filter(s=>snapshot.sourceStatus[s.id]?.status==="ok").length;
const sourceBody='<section class="page-head"><div><p class="eyebrow">SOURCE REGISTRY</p><h1>来源与更新状态</h1><p>优先使用发布方公开的 RSS 订阅源，所有资讯保留原文地址。</p></div></section><p class="source-summary">本轮 '+healthy+' / '+sources.length+' 个来源正常。失败来源保留历史记录，并在下一轮重试。</p><div class="table-wrap"><table><thead><tr><th>来源</th><th>频道</th><th>检查状态</th><th>最近成功</th><th>订阅源</th></tr></thead><tbody>'+sources.map(s=>{const state=snapshot.sourceStatus[s.id];return '<tr><td><a href="'+h(s.baseUrl)+'">'+h(s.name)+'</a></td><td>'+h(channels.find(c=>c.slug===s.channel)?.name)+'</td><td><span class="tag '+(state?.status==="ok"?'good':'warning')+'">'+(state?.status==="ok"?'正常':state?.error??'等待检查')+'</span></td><td>'+h(date(state?.lastSuccessAt))+'</td><td><a href="'+h(s.feedUrl)+'">RSS ↗</a></td></tr>';}).join("")+'</tbody></table></div>';
await output("sources/index.html",layout("来源与更新状态","公开来源及最近检查状态。","sources/",sourceBody,"sources"));
const about='<article class="record"><p class="eyebrow">ABOUT THE INFORMATION LAYER</p><h1>从来源出发，找到原文。</h1><p>世界信息汇是跨行业的自动资讯汇集页面。我们收集公开 RSS 中的标题、摘要、时间和原文地址，通过固定规则分类、去重与追踪更新。摘要最多截取240个字符，注明提供摘要的来源，不自动生成或补写事实。</p><h2>如何更新</h2><p>云端任务计划在每小时第7和37分钟运行，不依赖个人电脑保持开机。平台调度可能延迟。失败的来源不会生成虚构内容，会保留上次成功数据并标明状态。</p><h2>内容边界</h2><p>本站不使用模型生成长文，不转载全文或原文图片，不绕过登录与付费限制。完整文章在原发布方阅读。财经与健康频道仅提供来源导航，不生成投资或诊疗建议。</p><h2>机器读取</h2><p>主要内容直接输出为 HTML，并提供稳定条目地址、JSON Feed、RSS、Atom、JSON数据和网站地图。被搜索收录或被AI引用由检索系统决定。</p><div class="topic-links"><a href="'+href("api/v1/articles.json")+'">文章数据</a><a href="'+href("api/v1/sources.json")+'">来源数据</a><a href="'+href("sitemap.xml")+'">网站地图</a></div><h2>更正与来源退出</h2><p>原始来源、采集规则和数据变更在公开项目中可追踪。权利人可通过项目问题入口提出更正、移除或退出请求；可将来源禁用并将指定地址加入移除清单。</p><a href="https://github.com/billowssun/world-information-layer/issues">提出更正或来源退出请求 →</a></article>';
await output("about/index.html",layout("关于","自动汇集流程、内容边界及机器读取方式。","about/",about,"about"));
await output("404.html",layout("未找到记录","此地址不存在。","404.html",'<section class="page-head"><h1>未找到这条记录</h1></section><p><a href="'+href("")+'">返回资讯列表 →</a></p>',"all",null,true));
const recent=items.slice(0,100);
await output("feed.json",JSON.stringify({version:"https://jsonfeed.org/version/1.1",title:site.title,home_page_url:base,feed_url:absolute("feed.json"),language:"zh-CN",items:recent.map(i=>({id:absolute("articles/"+i.id+"/"),url:absolute("articles/"+i.id+"/"),external_url:i.originalUrl,title:i.title,content_text:(i.summary?i.summary+"\n\n":"")+"来源："+sourceNames(i)+"。完整内容请访问原文："+i.originalUrl,...(i.sourcePublishedAt&&!i.timeIssue?{date_published:i.sourcePublishedAt}:{}),date_modified:i.updatedAt,_provenance:{summary:i.summary??null,summary_provenance:i.summaryProvenance??null,source_ids:i.sourceIds,first_seen_at:i.firstSeenAt,source_published_at:i.sourcePublishedAt,time_issue:i.timeIssue}}))},null,2));
const x=v=>h(v).replaceAll("&#39;","&apos;");
await output("rss.xml",'<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>'+x(site.title)+'</title><link>'+x(base)+'</link><description>'+x(site.description)+'</description><atom:link href="'+x(absolute("rss.xml"))+'" rel="self" type="application/rss+xml"/>'+recent.map(i=>'<item><guid isPermaLink="false">'+i.id+'</guid><title>'+x(i.title)+'</title><link>'+x(absolute("articles/"+i.id+"/"))+'</link><description>'+x((i.summary?i.summary+"\n":"")+"来源："+sourceNames(i)+"；原文："+i.originalUrl)+'</description>'+(i.sourcePublishedAt&&!i.timeIssue?'<pubDate>'+new Date(i.sourcePublishedAt).toUTCString()+'</pubDate>':'')+'</item>').join("")+'</channel></rss>');
await output("atom.xml",'<?xml version="1.0" encoding="UTF-8"?><feed xmlns="http://www.w3.org/2005/Atom" xml:lang="zh-CN"><id>'+x(base)+'</id><title>'+x(site.title)+'</title><updated>'+snapshot.collectedAt+'</updated><author><name>世界信息汇来源整理</name></author><link rel="self" href="'+x(absolute("atom.xml"))+'"/><link href="'+x(base)+'"/>'+recent.map(i=>'<entry><id>'+x(absolute("articles/"+i.id+"/"))+'</id><title>'+x(i.title)+'</title><updated>'+i.updatedAt+'</updated><link href="'+x(absolute("articles/"+i.id+"/"))+'"/><link rel="related" href="'+x(i.originalUrl)+'"/><summary>'+x((i.summary?i.summary+"\n":"")+"来源："+sourceNames(i)+"；完整内容请阅读原文。")+'</summary></entry>').join("")+'</feed>');
await output("api/v1/articles.json",JSON.stringify({data:items,meta:{schemaVersion:"1",type:"source_record",count:items.length,collectedAt:snapshot.collectedAt}},null,2));
await output("api/v1/sources.json",JSON.stringify({data:sources.map(s=>({...s,status:snapshot.sourceStatus[s.id]})),meta:{schemaVersion:"1"}},null,2));
await output("api/v1/channels.json",JSON.stringify({data:channels.map(c=>({...c,count:totals.get(c.slug)}))},null,2));
await output("api/health.json",await readFile("data/health.json","utf8"));
const entries=[{path:"",modified:snapshot.collectedAt},{path:"sources/",modified:snapshot.collectedAt},{path:"about/",modified:null},...channels.map(c=>({path:"channels/"+c.slug+"/",modified:snapshot.collectedAt})),...items.map(i=>({path:"articles/"+i.id+"/",modified:i.updatedAt}))];
await output("sitemap.xml",'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+entries.map(e=>'<url><loc>'+x(absolute(e.path))+'</loc>'+(e.modified?'<lastmod>'+e.modified+'</lastmod>':'')+'</url>').join("")+'</urlset>');
await output("robots.txt","User-agent: *\nAllow: /\n\nSitemap: "+absolute("sitemap.xml")+"\n");
await output(".nojekyll","");
await output("build-info.json",JSON.stringify({collectedAt:snapshot.collectedAt,records:items.length,recordsWithSummary:items.filter(i=>i.summary).length,healthySources:healthy,sourceCount:sources.length,siteUrl:base,fileCount:written.length+1},null,2));
console.log("Rendered "+items.length+" real source records, "+channels.length+" channels, "+written.length+" files at "+base);
